export const EXPORTABLE_FIELDS = [
  "age_group",
  "gender",
  "department",
  "conditions",
  "allergies",
  "habits",
  "facial_profile",
  "facial_form",
  "symmetry",
  "tmj_status",
  "oral_hygiene",
  "upper_arch_form",
  "lower_arch_form",
  "upper_crowding_or_spacing",
  "lower_crowding_or_spacing",
  "molar_relationship",
  "canine_relationship",
  "overjet_mm",
  "overjet_classification",
  "overbite_percent",
  "overbite_classification",
  "crossbite",
  "midline_deviation",
  "skeletal_classification",
  "dental_findings",
  "fixed_appliances",
  "removable_appliances",
  "clear_aligners",
  "orthopedic_appliances",
  "surgical_treatment",
  "interceptive_treatment",
] as const;

export const FIELD_LABELS: Record<string, string> = {
  age_group:                  "Age Group",
  gender:                     "Gender",
  department:                 "Department",
  conditions:                 "Medical Conditions",
  allergies:                  "Allergies",
  habits:                     "Habits",
  facial_profile:             "Facial Profile",
  facial_form:                "Facial Form",
  symmetry:                   "Symmetry",
  tmj_status:                 "TMJ Status",
  oral_hygiene:               "Oral Hygiene",
  upper_arch_form:            "Upper Arch Form",
  lower_arch_form:            "Lower Arch Form",
  upper_crowding_or_spacing:  "Upper Crowding / Spacing",
  lower_crowding_or_spacing:  "Lower Crowding / Spacing",
  molar_relationship:         "Molar Relationship",
  canine_relationship:        "Canine Relationship",
  overjet_mm:                 "Overjet (mm)",
  overjet_classification:     "Overjet Classification",
  overbite_percent:           "Overbite (%)",
  overbite_classification:    "Overbite Classification",
  crossbite:                  "Crossbite",
  midline_deviation:          "Midline Deviation",
  skeletal_classification:    "Skeletal Classification",
  dental_findings:            "Dental Findings",
  fixed_appliances:           "Fixed Appliances",
  removable_appliances:       "Removable Appliances",
  clear_aligners:             "Clear Aligners",
  orthopedic_appliances:      "Orthopedic Appliances",
  surgical_treatment:         "Surgical Treatment",
  interceptive_treatment:     "Interceptive Treatment",
};
